import{a as E,S as q,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&c(h)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const p=15,A="52465106-83256c19c806c121527b257ca",P="https://pixabay.com/api/";async function b(r,o){const e={key:A,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:p};return(await E.get(P,{params:e})).data}const g=document.querySelector(".gallery"),u=document.querySelector(".btn-more"),L=document.querySelector(".box-loader");let x=new q(".gallery a",{captionsData:"alt",captionDelay:250});function S(r){const o=r.map(e=>`
      <li class="photo-card">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </li>
    `).join("");g.insertAdjacentHTML("beforeend",o),x.refresh()}function B(){g.innerHTML=""}function w(){L.classList.remove("is-hidden")}function f(){L.classList.add("is-hidden")}function v(){u.classList.remove("is-hidden")}function d(){u.classList.add("is-hidden")}const l=document.querySelector(".form"),y=l==null?void 0:l.querySelector('input[name="search-text"]');let m="",a=1,i=0;u&&u.addEventListener("click",$);l&&l.addEventListener("submit",M);d();f();async function M(r){r.preventDefault();const o=y==null?void 0:y.value.trim();if(!o){n.warning({title:"Warning",message:"Please enter a search query."});return}m=o,a=1,i=0,B(),d();try{w();const e=await b(m,a);i=e.totalHits??0;const c=Array.isArray(e.hits)?e.hits:[];if(c.length===0){n.info({title:"No results",message:"No images found. Try another query."}),f();return}S(c),n.success({title:"Success",message:`Hooray! We found ${i} images.`}),a*p<i?v():(d(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch(e){console.error(e),n.error({title:"Error",message:"Something went wrong. Please try again."})}finally{f()}}async function $(){a+=1;try{w();const r=await b(m,a),o=Array.isArray(r.hits)?r.hits:[];if(i=r.totalHits??i,o.length===0){d(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results."});return}S(o),F(),a*p>=i?(d(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):v()}catch(r){console.error(r),n.error({title:"Error",message:"Failed to load more images."}),a=Math.max(1,a-1)}finally{f()}}function F(){const r=g.querySelector(".photo-card");if(!r)return;const{height:o}=r.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
